select * from mytable limit 50;

-- Q1. What is the total revenue generated by male vs female customer?

select gender,sum(purchase_amount) as revenue
from mytable
group by gender;

-- Q2. Which customers used a discount but still more than the average purchase?

select customer_id,purchase_amount
from mytable
where discount_applied = 'yes' and purchase_amount >=(select avg(purchase_amount) from mytable);


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,avg(review_rating)
from mytable
group by item_purchased
order by avg(review_rating) desc limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express Shipping. 
 
 select shipping_type,round(avg(purchase_amount),2)
 from mytable
 where shipping_type in('Standard','Express')
 group by shipping_type;
 
-- Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
 
select subscription_status,count(customer_id),round(avg(purchase_amount),2),sum(purchase_amount)
from mytable
group by subscription_status
order by sum(purchase_amount),round(avg(purchase_amount),2) desc;

-- Q6. which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc limit 5;

-- Q7. Segment customers into new, Returning and Loyal based on their total number of previous purchases and show the count of each segment.

with customer_type as(
select customer_id,previous_purchases,
case 
    when previous_purchases = 1 then 'NEW'
    when previous_purchases between 2 and 10 then 'RETURNING'
    else 'LOYAL'
    end as customer_segment
from mytable
)
select customer_segment,count(*) as "Number Of Customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

with item_counts as(
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from mytable
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5 
group by subscription_status;

-- Q10. what is the revenue contribution of each age  group?

select age_group,sum(purchase_amount) as Total_revenue
from mytable
group by age_group
order by Total_revenue desc;



